#!/bin/bash

if [ "$1" = "folder" ]; then
  # Вывод списка файлов в длинном формате и их количество
  files=$(ls -l "$2" | tail -n +3)
  count=$(echo "$files" | wc -l)
  echo "Количество файлов: $count"
  echo "$files"
elif [ "$1" = "file" ]; then
  # Замена слова, удаление пятой строки и вывод измененного файла
  sed -i 's/слово/замена/g' "$2"
  sed -i '5d' "$2"
  cat "$2"
else
  echo "Некорректный первый аргумент. Допустимые значения: 'folder' или 'file'."
fi
